export const GALAXY_CONSTANTS = {
  CUBE_SIZE_LY: 10,
  CUBE_HALF_LY: 5,
  MIN_STARS_PER_CUBE: 5,
  MAX_STARS_PER_CUBE: 20,
  CUBE_CACHE_TTL_SECONDS: 120,
  GREEK_LETTERS: [
    'Alpha',
    'Beta',
    'Gamma',
    'Delta',
    'Epsilon',
    'Zeta',
    'Eta',
    'Theta',
    'Iota',
    'Kappa',
    'Lambda',
    'Mu',
    'Nu',
    'Xi',
    'Omicron',
    'Pi',
    'Rho',
    'Sigma',
    'Tau',
    'Upsilon',
  ],
} as const;
