export const SPAWN_CONSTANTS = {
  SEED_ORIGIN: { x: 0, y: 0, z: 0 },
  SPAWN_CUBE_SCAN_STEPS: 100,
  SPAWN_AXIS_ATTEMPTS: 6,
  SPAWN_REFERENCE_CUBE_ATTEMPTS: 10,
  SPAWN_STAR_ATTEMPTS: 20,
  SPAWN_FULL_ATTEMPTS: 5,
} as const;
